import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "Which EU countries offer financial incentives to blood donors?",
  "subtitle": "European member states offer a variety of monetary perks to motivate people to donate blood and blood components.",
  "colourSchemeClasses": 5,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,1,true,Incentives offered: Small tokens or symbolic gifts,,,,,,,,\nBelgium,BE,1,true,Incentives offered: Refreshments; Paid time off work,,,,,,,,\nBulgaria,BG,1,true,Incentives offered: Refreshments; Small tokens or symbolic gifts; Paid time off work; Compensation for donor's direct costs; Cash payment,,,,,,,,\nCyprus,CY,1,true,Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work,,,,,,,,\nCzechia,CZ,1,true,Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work; Tax relief; Health insurance benefits,,,,,,,,\nGermany,DE,1,true,Incentives offered: Compensation for donor's direct costs; Cash payment,,,,,,,,\nDenmark,DK,1,true,Incentives offered: Refreshments; Small tokens or symbolic gifts,,,,,,,,\nEstonia,EE,1,true,Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work,,,,,,,,\nGreece,EL,1,true,Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work; Compensation for donor's direct costs,,,,,,,,\nSpain,ES,0,false,,,,,,,,,\nFinland,FI,1,true,Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Compensation for donor's direct costs,,,,,,,,\nFrance,FR,1,true,Incentives offered: Small tokens or symbolic gifts; Paid time off work; Compensation for donor's direct costs,,,,,,,,\nCroatia,HR,1,true,Incentives offered: Refreshments; Small tokens or symbolic gifts; Paid time off work; Subsidised public transportation; Health insurance benefits,,,,,,,,\nHungary,HU,1,true,Incentives offered: Refreshments; Compensation for donor's direct costs,,,,,,,,\nIreland,IE,1,true,Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts,,,,,,,,\nItaly,IT,1,true,Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work,,,,,,,,\nLithuania,LT,1,true,Incentives offered: Small tokens or symbolic gifts; Paid time off work,,,,,,,,\nLuxembourg,LU,1,true,Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work,,,,,,,,\nLatvia,LV,1,true,Incentives offered: Small tokens or symbolic gifts; Paid time off work; Food vouchers; Compensation for donor's direct costs,,,,,,,,\nMalta,MT,1,true,Incentives offered: Refreshments; Paid time off work,,,,,,,,\nNetherlands,NL,1,true,Incentives offered: Refreshments; Medals of merit or recognition tokens; Health insurance benefits; Compensation for donor's direct costs,,,,,,,,\nPoland,PL,1,true,Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work; Subsidised public transportation; Tax relief,,,,,,,,\nPortugal,PT,1,true,Incentives offered: Tax relief,,,,,,,,\nRomania,RO,1,true,Incentives offered: Small tokens or symbolic gifts; Paid time off work; Subsidised public transportation; Food vouchers; Compensation for donor's direct costs,,,,,,,,\nSweden,SE,1,true,Incentives offered: Small tokens or symbolic gifts; Food vouchers,,,,,,,,\nSlovenia,SI,1,true,Incentives offered: Refreshments; Paid time off work,,,,,,,,\nSlovakia,SK,1,true,Incentives offered: Medals of merit or recognition tokens; Paid time off work; Food vouchers,,,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Small tokens or symbolic gifts",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Paid time off work",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Small tokens or symbolic gifts; Paid time off work; Compensation for donor's direct costs; Cash payment",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work; Tax relief; Health insurance benefits",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Compensation for donor's direct costs; Cash payment",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Small tokens or symbolic gifts",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work; Compensation for donor's direct costs",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Compensation for donor's direct costs",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Small tokens or symbolic gifts; Paid time off work; Compensation for donor's direct costs",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Small tokens or symbolic gifts; Paid time off work; Subsidised public transportation; Health insurance benefits",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Compensation for donor's direct costs",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Small tokens or symbolic gifts; Paid time off work",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Small tokens or symbolic gifts; Paid time off work; Food vouchers; Compensation for donor's direct costs",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Paid time off work",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Health insurance benefits; Compensation for donor's direct costs",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work; Subsidised public transportation; Tax relief",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Tax relief",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Small tokens or symbolic gifts; Paid time off work; Subsidised public transportation; Food vouchers; Compensation for donor's direct costs",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Small tokens or symbolic gifts; Food vouchers",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Refreshments; Paid time off work",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 1,
      "extraInfo": true,
      "text_content": "Incentives offered: Medals of merit or recognition tokens; Paid time off work; Food vouchers",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "binary",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "red",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "European Commission Joint Research Center",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://publications.jrc.ec.europa.eu/repository/handle/JRC134207",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": false,
  "customUnitLabel": "",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "Which EU countries offer financial incentives to blood donors?",
    "subtitle": "European member states offer a variety of monetary perks to motivate people to donate blood and blood components.",
    "textNoteDescription": "Note",
    "textNote": "",
    "textSourceDescription": "Source",
    "textSource": "European Commission Joint Research Center",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_AT": "Incentives offered: Small tokens or symbolic gifts",
    "extraInfo_BE": "Incentives offered: Refreshments; Paid time off work",
    "extraInfo_BG": "Incentives offered: Refreshments; Small tokens or symbolic gifts; Paid time off work; Compensation for donor's direct costs; Cash payment",
    "extraInfo_CY": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work",
    "extraInfo_CZ": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work; Tax relief; Health insurance benefits",
    "extraInfo_DE": "Incentives offered: Compensation for donor's direct costs; Cash payment",
    "extraInfo_DK": "Incentives offered: Refreshments; Small tokens or symbolic gifts",
    "extraInfo_EE": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work",
    "extraInfo_EL": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work; Compensation for donor's direct costs",
    "extraInfo_FI": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Compensation for donor's direct costs",
    "extraInfo_FR": "Incentives offered: Small tokens or symbolic gifts; Paid time off work; Compensation for donor's direct costs",
    "extraInfo_HR": "Incentives offered: Refreshments; Small tokens or symbolic gifts; Paid time off work; Subsidised public transportation; Health insurance benefits",
    "extraInfo_HU": "Incentives offered: Refreshments; Compensation for donor's direct costs",
    "extraInfo_IE": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts",
    "extraInfo_IT": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work",
    "extraInfo_LT": "Incentives offered: Small tokens or symbolic gifts; Paid time off work",
    "extraInfo_LU": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work",
    "extraInfo_LV": "Incentives offered: Small tokens or symbolic gifts; Paid time off work; Food vouchers; Compensation for donor's direct costs",
    "extraInfo_MT": "Incentives offered: Refreshments; Paid time off work",
    "extraInfo_NL": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Health insurance benefits; Compensation for donor's direct costs",
    "extraInfo_PL": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work; Subsidised public transportation; Tax relief",
    "extraInfo_PT": "Incentives offered: Tax relief",
    "extraInfo_RO": "Incentives offered: Small tokens or symbolic gifts; Paid time off work; Subsidised public transportation; Food vouchers; Compensation for donor's direct costs",
    "extraInfo_SE": "Incentives offered: Small tokens or symbolic gifts; Food vouchers",
    "extraInfo_SI": "Incentives offered: Refreshments; Paid time off work",
    "extraInfo_SK": "Incentives offered: Medals of merit or recognition tokens; Paid time off work; Food vouchers"
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_AT": "Incentives offered: Small tokens or symbolic gifts",
  "extraInfo_BE": "Incentives offered: Refreshments; Paid time off work",
  "extraInfo_BG": "Incentives offered: Refreshments; Small tokens or symbolic gifts; Paid time off work; Compensation for donor's direct costs; Cash payment",
  "extraInfo_CY": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work",
  "extraInfo_CZ": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work; Tax relief; Health insurance benefits",
  "extraInfo_DE": "Incentives offered: Compensation for donor's direct costs; Cash payment",
  "extraInfo_DK": "Incentives offered: Refreshments; Small tokens or symbolic gifts",
  "extraInfo_EE": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work",
  "extraInfo_EL": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work; Compensation for donor's direct costs",
  "extraInfo_FI": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Compensation for donor's direct costs",
  "extraInfo_FR": "Incentives offered: Small tokens or symbolic gifts; Paid time off work; Compensation for donor's direct costs",
  "extraInfo_HR": "Incentives offered: Refreshments; Small tokens or symbolic gifts; Paid time off work; Subsidised public transportation; Health insurance benefits",
  "extraInfo_HU": "Incentives offered: Refreshments; Compensation for donor's direct costs",
  "extraInfo_IE": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts",
  "extraInfo_IT": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work",
  "extraInfo_LT": "Incentives offered: Small tokens or symbolic gifts; Paid time off work",
  "extraInfo_LU": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work",
  "extraInfo_LV": "Incentives offered: Small tokens or symbolic gifts; Paid time off work; Food vouchers; Compensation for donor's direct costs",
  "extraInfo_MT": "Incentives offered: Refreshments; Paid time off work",
  "extraInfo_NL": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Health insurance benefits; Compensation for donor's direct costs",
  "extraInfo_PL": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work; Subsidised public transportation; Tax relief",
  "extraInfo_PT": "Incentives offered: Tax relief",
  "extraInfo_RO": "Incentives offered: Small tokens or symbolic gifts; Paid time off work; Subsidised public transportation; Food vouchers; Compensation for donor's direct costs",
  "extraInfo_SE": "Incentives offered: Small tokens or symbolic gifts; Food vouchers",
  "extraInfo_SI": "Incentives offered: Refreshments; Paid time off work",
  "extraInfo_SK": "Incentives offered: Medals of merit or recognition tokens; Paid time off work; Food vouchers"
});