import { writable } from 'svelte/store';

export const mapConfig = writable({
  "title": "Which EU countries offer financial incentives to blood donors?",
  "subtitle": "European member states offer a variety of monetary perks to motivate people to donate blood and blood components.",
  "colourSchemeClasses": 5,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,0,false,,,,,,,,,\nBelgium,BE,0,false,,,,,,,,,\nBulgaria,BG,1,true,Monetary incentives: compensation for donor's direct costs; cash payment.,,,,,,,,\nCroatia,HR,1,true,Monetary incentives: subsidised public transportation; health insurance benefits.,,,,,,,,\nCyprus,CY,0,false,,,,,,,,,\nCzechia,CZ,1,true,Monetary incentives: tax relief; health insurance benefits.,,,,,,,,\nDenmark,DK,0,false,,,,,,,,,\nEstonia,EE,0,false,,,,,,,,,\nFinland,FI,1,true,Monetary incentives: compensation for donor's direct costs.,,,,,,,,\nFrance,FR,1,true,Monetary incentives: compensation for donor's direct costs.,,,,,,,,\nGermany,DE,1,true,Monetary incentives: compensation for donor's direct costs; cash payment.,,,,,,,,\nGreece,EL,1,true,Monetary incentives: compensation for donor's direct costs.,,,,,,,,\nHungary,HU,1,true,Monetary incentives: compensation for donor's direct costs.,,,,,,,,\nIreland,IE,0,false,,,,,,,,,\nItaly,IT,0,false,,,,,,,,,\nLatvia,LV,1,true,Monetary incentives: food vouchers; compensation for donor's direct costs.,,,,,,,,\nLithuania,LT,0,false,,,,,,,,,\nLuxembourg,LU,0,false,,,,,,,,,\nMalta,MT,0,false,,,,,,,,,\nNetherlands,NL,1,true,Monetary incentives: health insurance benefits; compensation for donor's direct costs.,,,,,,,,\nPoland,PL,1,true,Monetary incentives: subsidised public transportation; tax relief.,,,,,,,,\nPortugal,PT,1,true,Monetary incentives: tax relief.,,,,,,,,\nRomania,RO,1,true,Monetary incentives: subsidised public transportation; food vouchers; compensation for donor's direct costs.,,,,,,,,\nSlovakia,SK,1,true,Monetary incentives: food vouchers.,,,,,,,,\nSlovenia,SI,0,false,,,,,,,,,\nSpain,ES,0,false,,,,,,,,,\nSweden,SE,1,true,Monetary incentives: food vouchers.,,,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: compensation for donor's direct costs; cash payment.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: subsidised public transportation; health insurance benefits.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: tax relief; health insurance benefits.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: compensation for donor's direct costs.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: compensation for donor's direct costs.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: compensation for donor's direct costs; cash payment.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: compensation for donor's direct costs.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: compensation for donor's direct costs.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: food vouchers; compensation for donor's direct costs.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: health insurance benefits; compensation for donor's direct costs.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: subsidised public transportation; tax relief.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: tax relief.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: subsidised public transportation; food vouchers; compensation for donor's direct costs.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: food vouchers.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 1,
      "extraInfo": true,
      "text_content": "Monetary incentives: food vouchers.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "binary",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "red",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "European Commission Joint Research Center",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "The report used for this visualization can be found on page 61 under the given link.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://publications.jrc.ec.europa.eu/repository/handle/JRC134207",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": false,
  "customUnitLabel": "",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "Which EU countries offer financial incentives to blood donors?",
    "subtitle": "European member states offer a variety of monetary perks to motivate people to donate blood and blood components.",
    "textNoteDescription": "Note",
    "textNote": "The report used for this visualization can be found on page 61 under the given link.",
    "textSourceDescription": "Source",
    "textSource": "European Commission Joint Research Center",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_BG": "Monetary incentives: compensation for donor's direct costs; cash payment.",
    "extraInfo_HR": "Monetary incentives: subsidised public transportation; health insurance benefits.",
    "extraInfo_CZ": "Monetary incentives: tax relief; health insurance benefits.",
    "extraInfo_FI": "Monetary incentives: compensation for donor's direct costs.",
    "extraInfo_FR": "Monetary incentives: compensation for donor's direct costs.",
    "extraInfo_DE": "Monetary incentives: compensation for donor's direct costs; cash payment.",
    "extraInfo_EL": "Monetary incentives: compensation for donor's direct costs.",
    "extraInfo_HU": "Monetary incentives: compensation for donor's direct costs.",
    "extraInfo_LV": "Monetary incentives: food vouchers; compensation for donor's direct costs.",
    "extraInfo_NL": "Monetary incentives: health insurance benefits; compensation for donor's direct costs.",
    "extraInfo_PL": "Monetary incentives: subsidised public transportation; tax relief.",
    "extraInfo_PT": "Monetary incentives: tax relief.",
    "extraInfo_RO": "Monetary incentives: subsidised public transportation; food vouchers; compensation for donor's direct costs.",
    "extraInfo_SK": "Monetary incentives: food vouchers.",
    "extraInfo_SE": "Monetary incentives: food vouchers."
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_AT": "Incentives offered: Small tokens or symbolic gifts",
  "extraInfo_BE": "Incentives offered: Refreshments; Paid time off work",
  "extraInfo_BG": "Monetary incentives: compensation for donor's direct costs; cash payment.",
  "extraInfo_CY": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work",
  "extraInfo_CZ": "Monetary incentives: tax relief; health insurance benefits.",
  "extraInfo_DE": "Monetary incentives: compensation for donor's direct costs; cash payment.",
  "extraInfo_DK": "Incentives offered: Refreshments; Small tokens or symbolic gifts",
  "extraInfo_EE": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work",
  "extraInfo_EL": "Monetary incentives: compensation for donor's direct costs.",
  "extraInfo_FI": "Monetary incentives: compensation for donor's direct costs.",
  "extraInfo_FR": "Monetary incentives: compensation for donor's direct costs.",
  "extraInfo_HR": "Monetary incentives: subsidised public transportation; health insurance benefits.",
  "extraInfo_HU": "Monetary incentives: compensation for donor's direct costs.",
  "extraInfo_IE": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts",
  "extraInfo_IT": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Small tokens or symbolic gifts; Paid time off work",
  "extraInfo_LT": "Incentives offered: Small tokens or symbolic gifts; Paid time off work",
  "extraInfo_LU": "Incentives offered: Refreshments; Medals of merit or recognition tokens; Paid time off work",
  "extraInfo_LV": "Monetary incentives: food vouchers; compensation for donor's direct costs.",
  "extraInfo_MT": "Incentives offered: Refreshments; Paid time off work",
  "extraInfo_NL": "Monetary incentives: health insurance benefits; compensation for donor's direct costs.",
  "extraInfo_PL": "Monetary incentives: subsidised public transportation; tax relief.",
  "extraInfo_PT": "Monetary incentives: tax relief.",
  "extraInfo_RO": "Monetary incentives: subsidised public transportation; food vouchers; compensation for donor's direct costs.",
  "extraInfo_SE": "Monetary incentives: food vouchers.",
  "extraInfo_SI": "Incentives offered: Refreshments; Paid time off work",
  "extraInfo_SK": "Monetary incentives: food vouchers."
});
